### ISSUE TITLE
Outputting Scan ID -- is that currently being set?

### ISSUE THREAD

**Issue by ssulei7** [Ostorlab/github_actions_ci#5]
Hi all,

I am working with a customer that is using this action to orchestrate Ostorlab scans against their mobile applications. One thing that I am working with them on is around being able to poll for results based off a scan ID.

I noticed in the action.yaml in your guys repository, contains the following:

```yaml
outputs:
  scan_id:
    description: id of the created scan.
  status:
    description: status of scan.
```

However, nowhere in the Dockerfile backend do I see any setting of said output. Is this something that can be done relatively quickly? I am more than happy to help implement that 😄
